apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-cloud-0710-01 
  janus-idp.io/tekton: test-cloud-0710-01
  backstage.io/kubernetes-id: test-cloud-0710-01
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-cloud-0710-01
resources: 
- application-dev.yaml